### ISSUE TITLE
Init and PostDisplay called even if the view has been destroyed

### ISSUE THREAD

**Issue by TimePerformance** [BriteSnow/brite#27]
In this case, view.$el is undefined which causes many errors.

Due to asynchroneous nature of brite apps, view can be destroyed before they had time to render. For instance, this is the case when a user quickly clicks on many menu items and views need to get data from the server.

**Comment by jeremychone** [comment]
For now, we just check the $el before the postDisplay (we will add .init check if needed, in another ticket)

**Comment by jeremychone** [comment]
fixed in 1.1.5.
